const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const lines=['booting isolated learning environment…','loading 4 course modules…','mapping SQL · XML · XPath · LDAP · NoSQL…','status: safe simulation / no database connection','ready. choose a module to begin.'];
const typer=$('#heroTyping');let li=0,ci=0;
function typeLine(){if(!typer||reduced){if(typer)typer.textContent=lines.at(-1);return}if(ci<lines[li].length){typer.textContent+=lines[li][ci++];setTimeout(typeLine,28)}else if(li<lines.length-1){setTimeout(()=>{const row=document.createElement('div');row.className='terminal-line';row.innerHTML='<span class="prompt">$</span> <span class="typing"></span>';$('#terminalBody').append(row);typer.removeAttribute('id');li++;ci=0;window.heroTyping=row.lastElementChild;typeInto(row.lastElementChild)},430)}}
function typeInto(el){if(ci<lines[li].length){el.textContent+=lines[li][ci++];setTimeout(()=>typeInto(el),28)}else if(li<lines.length-1){setTimeout(()=>{el.classList.remove('typing');const row=document.createElement('div');row.className='terminal-line';row.innerHTML='<span class="prompt">$</span> <span class="typing"></span>';$('#terminalBody').append(row);li++;ci=0;typeInto(row.lastElementChild)},430)}}
typeLine();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.09});$$('.reveal').forEach(el=>observer.observe(el));
$$('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{const parent=btn.closest('.content-block');$$('.tab-btn',parent).forEach(x=>x.classList.remove('active'));$$('.tab-content',parent).forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab).classList.add('active')}));
window.copyCode=async btn=>{const text=btn.closest('.code-block').querySelector('code').innerText;try{await navigator.clipboard.writeText(text);showToast('Copied to clipboard')}catch{showToast('Copy unavailable')}};
function showToast(text){const toast=$('#toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
$('#navToggle')?.addEventListener('click',()=>$('#navLinks').classList.toggle('open'));$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>$('#navLinks').classList.remove('open')));
const sections=$$('section[id]');const navLinks=$$('.nav-links a');const spy=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-25% 0px -70%'});sections.forEach(s=>spy.observe(s));
function analyze(){const value=$('#labInput').value;$('#unsafeQuery').textContent=`SELECT * FROM users WHERE username = '${value}'`;$('#boundValue').textContent=JSON.stringify(value);const structural=/['";]|--|\/\*|\b(or|and|union|select|drop)\b/i.test(value);$('#unsafeNote').innerHTML=structural?'<b>Boundary changed:</b> control-like tokens entered the SQL string.':'<b>Still fragile:</b> ordinary input appears valid, but concatenation remains unsafe.'}
$('#runLab')?.addEventListener('click',analyze);$('#labInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')analyze()});$$('.lab-presets button').forEach(b=>b.addEventListener('click',()=>{$('#labInput').value=b.dataset.value;analyze()}));analyze();
const checks=$$('.check-grid input');function progress(){const done=checks.filter(c=>c.checked).length;$('#checkProgress').textContent=`${done} / ${checks.length} complete`;$('#checkBar').style.width=`${done/checks.length*100}%`}checks.forEach(c=>c.addEventListener('change',progress));
